services:
  main:
    build:
      context: .
      args:
        # APP_PORT: 9015
        HTTPS_PROXY: socks5h://192.168.50.132:1090
        HTTP_PROXY: socks5h://192.168.50.132:1090
        GITURL: http://github.com/example-git        
    # environment:
    #   - APP_PORT=9015
    ports:
     - "9015:80"
    extra_hosts:
      - "docker-host:host-gateway"
#    command: 'python', '-m','app.mdsrv','--port','$PORT','--prefix','/mdsrv','1>','/data/stdout.log','2>','/data/stderr.log']
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /data
    volumes:
      - ./app:/opt/app
      - ./data/:/data/
      - /shared_data:/shared_data
